---
title: "Assignment 4:"
subtitle:  "Eu statistikk."
author: "Magnus Eidesmo og Harald Vika"
date: last-modified
date-format: "dddd D MMM, YYYY"
lang: en-GB
format:
  html: default
  typst:
    papersize: a4
  pdf: 
    documentclass: article
    number-sections: true
    keep-tex: true
    papersize: A4
    fig-pos: "H"
abstract: ""
editor: 
  markdown: 
    wrap: sentence
echo: false
---

```{r}
#| label: setup
#| message: false
library(tidyverse)
library(readxl)
library(restatapi)
library(DescTools)
library(ggrepel)
library(flextable)
library(modelr)
library(plm)
library(broom)
library(sandwich)
```

## Toc. eurostat
```{r}
# xml skal ha mer detaljert info
# toc_xml <- get_eurostat_toc()
# tekstversjonen har trolig nok info for vårt formål
toc_txt <- get_eurostat_toc(mode = "txt")
```


## GDP Nuts 3
```{r}
gdp_tabs <- toc_txt |> 
# Regex AND external to regex
   filter(
     str_detect(
       string = title,
       # For å matche både små og store bokstaver
       pattern = '[Gg][Dd][Pp]'
       # AND vha. &
       ) &
     str_detect(
       string = title,
       # For å matche både små og store bokstaver og
       # space eller ikke før 3
       pattern = '[Nn][Uu][Tt][Ss]\\s*3'
       )
     ) |> 
  select(title, code)
```

```{r}
gdp_tabs |> 
  select(title, code) |> 
  flextable()  |> 
  width(1, width = 3.5) |> 
  width(2, width = 1.5)
```


```{r}
# description nama_10r_3gdp
dsd_gdp <- get_eurostat_dsd("nama_10r_3gdp")
```


```{r}
dsd_gdp |> 
  filter(concept %in% c('freq', 'unit')) |> 
  flextable()  |> 
  width(j = 1, width = 1) |> 
  width(j = 2, width = 2) |> 
  width(j = 3, width = 2)
```

```{r}
dsd_gdp |> 
  filter(concept %in% c('geo')) |> 
  head(n = 10) |> 
  flextable()  |> 
  width(j = 1, width = 1) |> 
  width(j = 2, width = 2) |> 
  width(j = 3, width = 2)
```

```{r}
#| eval: true
#| cache: true
# Gross domestic product (GDP) at current market prices by NUTS 3 regions 
# id: nama_10r_3gdp
# Vi velger å hente samtlige soner for så å filtrere ut de få vi ikke trenger
gdp <- get_eurostat_data(
  id = "nama_10r_3gdp",
  filters = list(
    # neste linje viser hvordan vi kunne ha hentet ut data
    # for spesifiserte land
    # geo = c("AT", "DE", "DK", "FR"),
    nuts_level = "3",
    unit = "MIO_PPS_EU27_2020"
  ),
  exact_match = FALSE,
  date_filter = 2000:2023,
  stringsAsFactors = FALSE
  ) |> 
  mutate(
    gdp_n3 = 1000000 * values
  ) |> 
  select(-c(unit, values)) |> 
  # Vil bare ha NUTS 3 nivå (5 karakterer). Vil aggregere selv til NUTS2,
  # NUTS1 og NUTSc  
  filter(str_length(geo) == 5) |> 
  as_tibble()
```


```{r}
dim(gdp)
```

```{r}
gdp
```

```{r}
gdp |> 
  filter(geo == "IE053") |> 
  print(n = 25)
```

```{r}
ie_data <- tibble(
  geo = c("IE053", "IE053", "IE053"),
  time = c("2015", "2016", "2017"),
  gdp_n3 = c(NA, NA, NA)
)
```

```{r}
gdp <- rbind(gdp, ie_data)
```

```{r}
gdp <- gdp |> 
  arrange(geo, time) |> 
  mutate(
    gdp_n3 = zoo::na.approx(gdp_n3)
  )
```

```{r}
gdp |> 
  filter(geo == "IE053") |> 
  print(n = 25)
```

# Population demo_r_pjanaggr3

## oppgave 1
Søker i toc_txt for tabeller
```{r}
pop_tabs <- toc_txt |>
  filter(
    # Matcher både population og Population
    str_detect(
      string = title,
      pattern = "[Pp][Oo][Pp][Uu][Ll][Aa][Tt][Ii][Oo][Nn]"
    ) &
    # Matcher både NUTS3 og NUTS 3
    str_detect(
      string = title,
      pattern = "[Nn][Uu][Tt][Ss]\\s*3"
    )
  ) |>
  select(title, code)


```



## oppgave 2
###(i)
```{r}
pop_tabs |>
  filter(
    str_detect(title, regex("population", ignore_case = TRUE)) &
    str_detect(title, regex("NUTS\\s*3", ignore_case = TRUE))
  )

```

```{r}
pop_tabs |>
  filter(
    str_detect(
      title,
      fixed("Average annual population to calculate regional GDP data (thousand persons) by NUTS 3 region")
    )
  ) |>
  select(code)
```
Finner at koden er demo_r_pjanaggr3 for tabellen med forklarende tekst «Average annual population to calculate regional GDP data (thousand persons) by NUTS 3 regions»

###(ii)

```{r}
dsd_pop <- get_eurostat_dsd("demo_r_pjanaggr3")
```

###(iii)


### (v)

```{r}
#| eval: true
#| cache: true
pop <- get_eurostat_data(
 id = "nama_10r_3popgdp",
 filters = list(
 nuts_level = "3",
 unit = "THS"
 ),
 exact_match = FALSE,
 date_filter = 2000:2023,
 stringsAsFactors = FALSE
 ) |>
 mutate(
 pop_n3 = values * 1000
 ) |> 
  select(-c(unit, values)) |>
 filter(str_length(geo) == 5) |> 
 as_tibble()
```

```{r}
dim(pop)
```






